# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Dot Campus Blog"
author: "DotCampus"
description: "This blog shares knowledge, tips and experience regarding software development and tech in general." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
url: "https://blog.dotcampus.co" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
twitter_username: "DotCampusHQ"
github_username: "DotCampus"
support_email: "support@dotcampus.co"
phone_number: "+2348189805679"
# linkedin_username: "dotcampus-co"
# email: "support@dotcampus.co"
#facebook_username: username
#instagram_username: username

google_analytics: true # Set to true to enable Google Analytics tracking
allow_comments: true # Set to false to disable comments on all posts
apply_now_url: "https://forms.gle/WEkKgxyyNuDxZ41E7" # Set to the URL of the apply now page

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

paginate: 12
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
